version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080